##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Thu Jun 11 07:50:36 CEST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32l4d


######################################
# building variables
######################################
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
# threadx path
THREADX_DIR = src/threadx

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/core/main.c \
src/core/system_stm32l4xx.c \
src/core/sysmem.c \
src/core/syscalls.c \
src/data/data.c \
src/drivers/mcu/mcu.c \
src/drivers/timers/timer.c \
src/mcal/i2c.c \
src/mcal/adc.c \
src/ecal/pcf8563.c \
src/utils/fifo/fifo.c \
src/utils/fifo/fifo_test.c \
src/utils/random/random.c \
test/tests.c \
src/threadx/app/tx_app.c

# ASM sources
ASM_SOURCES =  \
startup_stm32l475xx.s

# ASMM sources
ASMM_SOURCES = \
src/core/tx_initialize_low_level.S

######################################
# THREADX sources
PORT_DIR = $(THREADX_DIR)/ports/cortex_m4/gnu/src
COMMON_DIR = $(THREADX_DIR)/common/src

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32L475xx


# AS includes
AS_INCLUDES = \
-I$(THREADX_DIR)/common/inc \
-I$(THREADX_DIR)/ports/cortex_m4/gnu/inc

# C includes
C_INCLUDES =  \
-Isrc/core \
-Isrc/data \
-Isrc/drivers/CMSIS/Device/ST/STM32L4xx/Include \
-Isrc/drivers/CMSIS/Core/Include \
-Isrc/drivers/mcu \
-Isrc/drivers/timers \
-Isrc/mcal \
-Isrc/common \
-Isrc/drivers \
-Isrc/ecal \
-Isrc/utils/fifo \
-Isrc/utils/random \
-Itest \
-I$(THREADX_DIR)/common/inc \
-I$(THREADX_DIR)/app \
-I$(THREADX_DIR)/ports/cortex_m4/gnu/inc

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

# add debug
CFLAGS += -g 

# Generate dependency information
#CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L475XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR = $(THREADX_DIR)/libthreadx.a
#LIBDIR = threadx/build/libthreadx.a 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) makefile $(LIBDIR)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# flash
#######################################
flash: all
	openocd -f interface/stlink.cfg -f target/stm32l4x.cfg -c "program build/stm32l4.bin verify reset exit 0x08000000"
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
