#include "timer.h"

void tim17_init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_TIM17EN;

    // Set Prescaler (4000000 / 4000 = 1000 Hz counting frequency)
    TIM17->PSC = 3999;

    // 50 ticks * 1ms = 50ms period
    TIM17->ARR = 49;

    // Enable Update Interrupt
    TIM17->DIER |= TIM_DIER_UIE;

    // Force an update event to reload PSC and ARR immediately into shadow registers
    TIM17->EGR |= TIM_EGR_UG;

    // Clear the update flag generated by the EGR->UG bit to prevent immediate ISR execution
    TIM17->SR &= ~TIM_SR_UIF;

    // Enable the timer counter
    TIM17->CR1 |= TIM_CR1_CEN;

}
void tim7_init(void)
{
    RCC->APB1ENR1 |= RCC_APB1ENR1_TIM7EN;

    // Set Prescaler (4000000 / 4000 = 1000 Hz counting frequency)
    TIM7->PSC = 3999;

    // Set Auto-Reload value (1000 Hz / 100 ticks = 10 Hz / 100ms period)
    TIM7->ARR = 99;

    // Enable Update Interrupt
    TIM7->DIER |= TIM_DIER_UIE;

    // Force an update event to reload PSC and ARR immediately into shadow registers
    TIM7->EGR |= TIM_EGR_UG;

    // Clear the update flag generated by the EGR->UG bit to prevent immediate ISR execution
    TIM7->SR &= ~TIM_SR_UIF;

    // Enable the timer counter
    TIM7->CR1 |= TIM_CR1_CEN;

}
void tim6_init(void)
{
    RCC->APB1ENR1 |= RCC_APB1ENR1_TIM6EN;

    // Set Prescaler (4000000 / 4000 = 1000 Hz counting frequency)
    TIM6->PSC = 3999;

    // Set Auto-Reload value (1000 Hz / 100 ticks = 10 Hz / 100ms period)
    TIM6->ARR = 99;

    // Enable Update Interrupt
    TIM6->DIER |= TIM_DIER_UIE;

    // Force an update event to reload PSC and ARR immediately into shadow registers
    TIM6->EGR |= TIM_EGR_UG;

    // Clear the update flag generated by the EGR->UG bit to prevent immediate ISR execution
    TIM6->SR &= ~TIM_SR_UIF;

    // Enable the timer counter
    TIM6->CR1 |= TIM_CR1_CEN;

}

extern void main_loop(void);
extern void error_loop(void);
extern void sensor_loop(void);

void TIM1_TRG_COM_TIM17_IRQHandler(void)
{
    // Check if the Update Interrupt Flag is active
    if (TIM17->SR & TIM_SR_UIF)
    {
        // Clear the interrupt flag (CRITICAL: Do this first to prevent re-triggering)
        TIM17->SR &= ~TIM_SR_UIF;

        // --- PLACE YOUR 50ms CODE HERE ---
        sensor_loop();
    }
}

void TIM7_IRQHandler(void)
{
    // Check if the update interrupt flag is set
    if (TIM7->SR & TIM_SR_UIF) {
        // Clear the update interrupt flag
        TIM7->SR &= ~TIM_SR_UIF;
        
        // Add your 100ms recurring user code here
        error_loop();
    }
}

void TIM6_DAC_IRQHandler(void) {
    // Check if the update interrupt flag is set
    if (TIM6->SR & TIM_SR_UIF) {
        // Clear the update interrupt flag
        TIM6->SR &= ~TIM_SR_UIF;
        
        // Add your 100ms recurring user code here
        main_loop();
    }
}

void tim2_init(void) {

    // 1. Enable the clock for TIM2 in the RCC register
    RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;

    // 1. Set your values (they go into the preload buffer)
    TIM2->PSC = 3999; // 1kHz timer @4MHz
    TIM2->ARR = 0xFFFFFFFF; // maximum value -> not needed by delay function

    // 2. Safely apply the values instantly
    TIM2->EGR = TIM_EGR_UG;   // Force the update

    // 3. WIPE OUT THE SIDE EFFECTS
    TIM2->SR = 0;             // Clear the Status Register completely

    // 4. Reset the counter register
    TIM2->CNT = 0;
    
    // 5. Enable the timer counter
    TIM2->CR1 |= TIM_CR1_CEN;
}

void tim2_delay_ms(uint32_t ms) {
    // Reset the counter to 0 before starting the delay
    TIM2->CNT = 0;
    
    // Wait until the counter reaches the desired millisecond value
    while (TIM2->CNT < ms) {
        // Do nothing, just loop until time passes
    }
}
/*
void init_timer1(void)
{
	volatile uint32_t dmy __attribute__ ((unused));
	
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	dmy = RCC->APB2ENR;

	TIM1->PSC = (41999 & TIM_PSC_PSC); // 2000 Hz
	TIM1->ARR = (1999 & 0xffff); // Timer1 = 1s
	TIM1->DIER |= TIM_DIER_UIE;

	__NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);
	TIM1->CR1 |= TIM_CR1_CEN;
}

void timer1_delay(uint32_t ms)
{
	// Delay in number of timer ticks
	uint32_t delay = (ms * 2) - 1;
	uint32_t cnt = TIM1->CNT;
	uint32_t cnt_limit = (cnt + delay) % TIM1->ARR;
	printf("cnt: %d%tcnt_limit: %d\n", cnt, cnt_limit);
	while (TIM1->CNT != cnt_limit) {};
}
*/